I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/turn.rpy", line 169, in script call
    call before_start
  File "game/script.rpy", line 23, in script
    show live2dtest testani with dissolve
Exception: Image 'live2dtest' does not accept attributes 'testani'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/turn.rpy", line 169, in script call
    call before_start
  File "game/script.rpy", line 23, in script
    show live2dtest testani with dissolve
  File "D:\renpy-7.4.4-sdk\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\renpy-7.4.4-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "D:\renpy-7.4.4-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\renpy-7.4.4-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "D:\renpy-7.4.4-sdk\renpy\display\layout.py", line 155, in _duplicate
    args.extraneous()
  File "D:\renpy-7.4.4-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'live2dtest' does not accept attributes 'testani'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
untitled 0.2
Tue Apr 25 17:52:00 2023
